# change the followings to match your Github username and repo name
baseurl: "/maia" # the name of your github repo
url: "https://itsmaia.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Maia's corner"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Gustavo Maia
author-bio: Programador freelancer, ajudo as pessoas a aprenderem japonês no  # change to false to hide
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: Sobre
  permalink: about

# use false to turn off any social media links
twitter: https://twitter.com/
facebook: https://facebook.com/
instagram: https://instagram.com/
github: https://github.com/
linkedin: https://linkedin.com/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
