# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://itsmaia.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Maia's corner"
description: Just a place to present myself :)

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Gustavo Maia
author-bio: Programador freelancer, ajudo as pessoas a aprenderem japonês no # change to false to hide
author-image: luigi.jpg # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
  - text: Sobre
    permalink: about
  - text: Contato
    permalink: contato

# use false to turn off any social media links
github: https://github.com/itsmaia
linkedin: https://www.linkedin.com/in/gustavo-meneses/
medium: false
google-scholar: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

google-analytics: G-C3L2TM6TL4

# jekyll plugins - no need to change
plugins:
  - jekyll-seo-tag
